# Generated by Django 3.0 on 2023-11-01 11:03

from django.db import migrations

def copy_data(apps, schema_editor):
    NewAddress = apps.get_model('lettings', 'Address')
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    
    NewAddress.objects.bulk_create(
        NewAddress(id=old_object.id,
                number=old_object.number,
                street=old_object.street,
                city=old_object.city,
                state=old_object.state,
                zip_code=old_object.zip_code,
                country_iso_code=old_object.country_iso_code)
        for old_object in OldAddress.objects.all()
    )

    NewLetting = apps.get_model('lettings', 'Letting')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    
    lettings = []
    for old_object in OldLetting.objects.all() :
        letting = NewLetting(id=old_object.id, title = old_object.title)
        letting.address = NewAddress.objects.get(id=old_object.address.id)
        lettings.append(letting)
    NewLetting.objects.bulk_create(lettings)
    
def reverse_copy_data(apps, schema_editor):
    NewAddress = apps.get_model('lettings', 'Address')
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    
    OldAddress.objects.bulk_create(
        OldAddress(id=new_object.id,
                number=new_object.number,
                street=new_object.street,
                city=new_object.city,
                state=new_object.state,
                zip_code=new_object.zip_code,
                country_iso_code=new_object.country_iso_code)
        for new_object in NewAddress.objects.all()
    )

    NewLetting = apps.get_model('lettings', 'Letting')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')

    old_lettings = []
    for object in NewLetting.objects.all() :
        old_letting = OldLetting(id=object.id, title = object.title)
        old_letting.address = OldAddress.objects.get(id=object.address.id)
        old_lettings.append(old_letting)
    OldLetting.objects.bulk_create(old_lettings)
    

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(copy_data, reverse_code=reverse_copy_data, elidable=True)
    ]
