version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.2
  python: circleci/python@2.1.1

workflows:
  build-deploy:
    jobs:
      - compile-and-test:
          context:
            - oc-letting-django
      - build:
          requires:
            - compile-and-test
          filters:
            branches:
              only: master
      - aws-ecr/build_and_push_image:
          requires:
            - build
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::236776589655:role/AWSEC2ForOcLetting
                aws-region: $AWS_DEFAULT_REGION
          repo: 236776589655.dkr.ecr.eu-west-3.amazonaws.com/oc-letting
          tag: latest
          context:
              - aws

jobs:
  compile-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          args: "--dev"
      - run:
          name: Verify linting
          command: |
            pipenv run flake8 --max-line-length=127
      - run:
          name: Testing
          command: |
            pipenv run pytest
  build:
    docker:
      - image: cimg/python:3.11
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t benjaminb2/oc-lettings:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push benjaminb2/oc-lettings:$TAG
