version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.2
  python: circleci/python@2.1.1

workflows:
  build-deploy:
    jobs:
      - linting
      - python/test:
          requires:
            - linting
          args: "--dev"
          pkg-manager: pipenv
          test-tool: pytest
      # couverture > 80%
      - build:
          requires:
            - python/test
          filters:
            branches:
              only: main
      - aws-ecr/build_and_push_image:
          requires:
            - python/test
            - build
          filters:
            branches:
              only: main
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::236776589655:role/AWSEC2ForOcLetting
          repo: 236776589655.dkr.ecr.eu-west-3.amazonaws.com/oc-letting
          tag: latest

jobs:
  linting:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          args: flake8
          pkg-manager: pipenv
      - run:
          name: Verify linting
          command: |
            pipenv run flake8 --max-line-length=127
  build:
    docker:
      - image: cimg/python:3.11
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t BenjaminB2/oc-lettings:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push BenjaminB2/oc-lettings:$TAG
